version: "3"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    depends_on:
      - api
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DB_SOURCE=postgresql://root:secret@localhost:5432/order?sslmode=disable

